### ISSUE TITLE
DataGridWithFilterDemo doesn't reference the other project

### ISSUE THREAD

**Issue by sashoalm** [DartAlex/DataGridViewWithFilter#1]
The repo is organized into 2 separate project, and the demo app depends on the lib, but it doesn't reference it, so trying to compile from a fresh clone fails with the error:

```
error CS0246: The type or namespace name 'DataGridViewWithFilter' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by DartAlex** [comment]
Fixed namespace, now the demo is works.
